app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from routes import main

app = Flask(__name__)
app.config['DEBUG'] = True

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///foodtracker.db'
# app.config['SQLALCHEMY_DATABASE_URI']='mysql://root:root@localhost:3306/foodtracker'
app.config['SQLAlCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app=app) #for binding flask app

app.register_blueprint(main)

log_food = db.Table('log_food',
    db.Column('log_id', db.Integer, db.ForeignKey('log.id'), primary_key=True),
    db.Column('food_id', db.Integer, db.ForeignKey('food.id'), primary_Key=True)
)

class Food(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    proteins = db.Column(db.Integer, nullable=False)
    carbs = db.Column(db.Integer, nullable=False)
    fats = db.Column(db.Integer, nullable=False)

    @property
    def calories(self):
        return self.proteins*4 + self.carbs*4 + self.fats*9


class Log(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    track = db.relationship('Food', secondary=log_food)

def create_app():
    return 'test'

if __name__=='__main__':
    db.create_all()  #to create table through model class
    app.run(debug=True)

routes.py
from flask import Flask,Blueprint, app, render_template, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

app = Flask(__name__)
app.config['DEBUG'] = True
db = SQLAlchemy(app=app) #for binding flask app

main = Blueprint('main',__name__,template_folder='templates')

from app import Food

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/add')
def add():
    foods = Food.query.all()
    return render_template('add.html', foods=foods, food=None)

@main.route('/add', methods=['POST'])
def add_post():
    food_name = request.form.get('food-name')
    proteins = request.form.get('protein')
    carbs = request.form.get('carbohydrates')
    fats = request.form.get('fat')

    food_id = request.form.get('food-id')

    if food_id:
        food = Food.query.get(food_id)
        food.name = food_name
        food.proteins = proteins
        food.carbs = carbs
        food.fats = fats
    else:
        new_food = Food(
            name=food_name,
            proteins=proteins,
            carbs=carbs,
            fats=fats
        )

        db.session.add(new_food)
    db.session.commit()
    return redirect(url_for('main.add'))

@main.route('/delete_food/<int:food_id>')
def delete_food(food_id):
    food = Food.query.get(food_id)
    db.session.delete(food)
    db.session.commit()
    return redirect(url_for('main.add'))

@main.route('/edit_food/<int:food_id>')
def edit_food(food_id):
    food = Food.query.get(food_id)
    foods = Food.query.all()
    return render_template('add.html', food=food, foods=foods)

@main.route('/view')
def view():
    return render_template('view.html')

templates/add.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | Add Food Item</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">

			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>

					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="./" title="Home">Home</a>
							  </li>
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-plus-sign"></i> New Food Form
							</h3>
							<hr />

							<form action="{{ url_for('main.add') }}" method="POST" role="form">

								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
											<label for="food-name">Food Name</label>
						                  	<input type="text" class="form-control" id="food-name" name="food-name" placeholder="Food Name" value="{{ food.name }}" autofocus>
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="protein">Protein</label>
						                  <input type="number" class="form-control" id="protein" name="protein" placeholder="Protein" value="{{ food.proteins }}">
						                </div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="carbohydrates">Carbohydrates</label>
						                  <input type="number" class="form-control" id="carbohydrates" name="carbohydrates" placeholder="Carbohydrates" value="{{ food.carbs }}">
						                </div>
									</div>
								</div>

								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="fat">Fat</label>
						                  <input type="number" class="form-control" id="fat" name="fat" placeholder="Fat" value="{{ food.fats }}">
						                </div>
									</div>

									<div class="col-lg-4">
										<div class="form-group">
											<label style="visibility:hidden">submit</label>
											<input type="hidden" name="food-id" value="{{ food.id }}">
											<button type="submit" class="btn btn-primary btn-block">
												<i class="glyphicon glyphicon-upload"></i> Submit
											</button>
										</div>
									</div>
								</div>

							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h4 class="lean-h text-black">
								<i class="glyphicon glyphicon-th-list"></i> Existing Food Items
							</h4>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 10%;">Protein</th>
										<th style="width: 16%;">Carbohydrates</th>
										<th style="width: 10%;">Fat</th>
										<th style="width: 12%;">Calories</th>
										<th style="width: 20%;">Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for food in foods %}
									<tr>
										<td>{{ food.id }}</td><td>{{ food.name }}</td><td>{{ food.proteins }}</td>
										<td>{{ food.carbs }}</td><td>{{ food.fats }}</th><td>{{ food.calories }}</td>
										<td>
											<a href="{{ url_for('main.edit_food', food_id=food.id) }}" class="btn btn-default btn-xs">
												<i class="glyphicon glyphicon-pencil"></i> Edit
											</a>
											<a href="{{ url_for('main.delete_food', food_id=food.id) }}" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | Home</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">

			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>

					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4  col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="" method="POST" role="form">

								<div class="form-group">
									<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
									<div class="input-group">
									  <input type="date" class="form-control" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Date
										</button>
									  </span>
									</div>
								</div>

							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-12">
					<h4 class="text-center text-white"><strong>Existing Records (30)</strong></h4>
				</div>
			</div>

			<div class="row t20">
				<div class="col-md-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> December 14, 2017

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view') }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">60</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">49</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">55</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">955</span> Calories</li>
						</ul>
					</div>
				</div>
				<div class="col-md-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> December 14, 2017

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view') }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">60</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">49</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">55</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">955</span> Calories</li>
						</ul>
					</div>
				</div>
				<div class="col-md-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> December 14, 2017

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view') }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">60</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">49</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">55</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">955</span> Calories</li>
						</ul>
					</div>
				</div>
				<div class="col-md-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> December 14, 2017

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view') }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">60</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">49</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">55</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">955</span> Calories</li>
						</ul>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

templates/view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | View Details</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">

			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>

					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="" method="POST" role="form">

								<div class="form-group">
									<label>Add Food</label>
									<div class="input-group">
									  <select class="form-control" name="food-select">
					                        <option value=1>Burger</option>

					                        <option value=2>Pizza</option>

					                        <option value=3>Shake</option>

					                        <option value=4>Burrito</option>

					                        <option value=5>Steak</option>

					                        <option value=6>Banana</option>

					                        <option value=7>Pasta</option>
					                    </select>
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Food
										</button>
									  </span>
									</div>
								</div>

							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-calendar"></i> December 14, 2017
							</h3>

							<div class="row">
								<div class="col-lg-3">
									<h4 class="lean-h">
										Protein: &nbsp;<strong class="f25">60</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Carbohydrates: <strong class="f25">55</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Fat: <strong class="f25">55</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Calories: <strong class="f25">955</strong>
									</h4>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 10%;">Protein</th>
										<th style="width: 16%;">Carbohydrates</th>
										<th style="width: 10%;">Fat</th>
										<th style="width: 12%;">Calories</th>
										<th style="width: 20%;">Actions</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>1</td><td>Burger</td><td>20</td>
										<td>25</td><td>15</th><td>315</td>
										<td>
											<a href="#" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a>
										</td>
									</tr>
									<tr>
										<td>2</td><td>Burger</td><td>20</td>
										<td>25</td><td>15</th><td>315</td>
										<td>
											<a href="#" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>
© 2021 GitHub, Inc.